### ISSUE TITLE
How to install and configure for Model Driven App

### ISSUE THREAD

**Issue by darrenlock** [hzengindev/survey-management#1]
HI, I've installed the Solution file into my environment and I'm able to access the Entities and Forms. How do I install the PCF and configure it to initiate and complete a survey response?

**Comment by hzengindev** [comment]
Actually there is a managed solution file under the this [link](https://github.com/hzengindev/survey-management/blob/main/src/dataverse-customization/SurveyManagement_1_0_0_1.zip) Maybe it will help you.

**Comment by darrenlock** [comment]
That's the Solution I imported to get the Entities & Forms but unless I'm doing something wrong on import, there doesn't appear to be a PCF control inside the solution:
![image](https://user-images.githubusercontent.com/19533550/156538977-c3627b48-4012-4c3e-a01f-4f33fb50c39d.png)

**Comment by hzengindev** [comment]
I got it. Actually entity form customizations and pcf solution are different things and that's why I didn't import pcf files in main solutions. You can access the pcf solution this [link](https://github.com/hzengindev/survey-management/blob/main/src/dataverse-customization/SMCSolutions.zip).

**Comment by darrenlock** [comment]
I now have everything working, thank you. I'm now trying to work out the best approach for associating the Survey Request with my Order entity. I have a One to Many relationship between my Order and Survey Request. Using a subgrid on the Order form I can create new (associated) Survey Request(s). I'm now looking for the best way to initiate the Survey screen. I've added a Lookup field to the Order from which I can select an existing Survey Request. I duplicate this field on the form and use the PCF control to display the Survey for the User to complete (the User has to do an Order Save and Refresh for the PCF to pick this up). But I cannot find a way of filtering this look up to only return Survey Requests previously associated with this Order? The ideal User Experience would be a view where I can display a list of incomplete Survey Requests for the Order and the User selects the Survey Request they want to complete.
