### ISSUE TITLE
Survey requires Answer Options Template

### ISSUE THREAD

**Issue by darrenlock** [hzengindev/survey-management#2]
If I create a Survey with Answers without using an Answer Option Template as follows:
![image](https://user-images.githubusercontent.com/19533550/157235295-a7db1022-8179-4679-a93f-d14c20d30b06.png)

I get the following error:
![image](https://user-images.githubusercontent.com/19533550/157235347-c0f6c015-f5e5-463c-825f-e9db0a5f67c2.png)

As soon as I use a template the error goes away and the Survey works correctly.

**Comment by hzengindev** [comment]
Hi @darrenlock, I fixed this issue. Re-import the new solution file [link](https://github.com/hzengindev/survey-management/blob/main/src/dataverse-customization/SurveyManagement_1_0_0_2.zip) and it will be fixed.
